# Build Stage
FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Run Stage
FROM mcr.microsoft.com/playwright/java:v1.41.0-jammy
WORKDIR /app
COPY --from=build /app/digital-promoter/target/*.jar app.jar
EXPOSE 8084
ENTRYPOINT ["java", "-jar", "app.jar"]